# Generated by Django 3.1.7 on 2021-04-26 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name': 'Reservation'},
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=30)),
                ('date_of_birth', models.DateTimeField(verbose_name='Closing Date')),
                ('reason_for_registering', models.TextField(null=True)),
                ('start_date', models.DateTimeField(verbose_name='Occasion Date')),
                ('exp_date', models.DateTimeField(verbose_name='Closing Date')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.package')),
            ],
        ),
        migrations.AlterField(
            model_name='ticketnumber',
            name='ticket',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='account.members'),
        ),
    ]
