# Generated by Django 3.1.7 on 2021-05-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210426_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name': 'Packages'},
        ),
        migrations.AddField(
            model_name='members',
            name='barcode',
            field=models.ImageField(blank=True, upload_to='barcodes'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='date_of_birth',
            field=models.DateTimeField(verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='members',
            name='exp_date',
            field=models.DateTimeField(verbose_name='Expiring Date'),
        ),
        migrations.AlterField(
            model_name='members',
            name='start_date',
            field=models.DateTimeField(verbose_name='Registration Date'),
        ),
    ]
