# Generated by Django 3.1.7 on 2021-05-04 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210501_0555'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailySchedule',
        ),
    ]
