# Generated by Django 3.1.7 on 2021-05-04 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_delete_dailyschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
