# Generated by Django 3.1.7 on 2021-05-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_delete_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='closing_date',
        ),
        migrations.RemoveField(
            model_name='package',
            name='event_banner',
        ),
        migrations.RemoveField(
            model_name='package',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='members',
            name='reason_for_registering',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
