# Generated by Django 2.2.23 on 2021-05-24 03:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210504_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laundry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50, verbose_name='Customer Name')),
                ('custom_number', models.IntegerField(verbose_name='Customer')),
                ('shirt', models.IntegerField(verbose_name='T-Shirt')),
                ('trouser', models.IntegerField(verbose_name='Trouser/Short')),
                ('underwear', models.IntegerField(verbose_name='Single/Boxers')),
                ('native', models.IntegerField(verbose_name='Complete Native')),
                ('duvet', models.IntegerField(verbose_name='Duvet')),
                ('duver_beddings', models.IntegerField(verbose_name='Duvet and Beddings')),
                ('towel', models.IntegerField(verbose_name='Towel')),
                ('dropp_off', models.DateTimeField(auto_now=True)),
                ('commission', models.CharField(max_length=200, verbose_name='Refered Byss')),
            ],
        ),
        migrations.AddField(
            model_name='members',
            name='refered_by',
            field=models.CharField(default=datetime.datetime(2021, 5, 24, 3, 32, 59, 606934, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='members',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
