# Generated by Django 2.2.23 on 2021-05-25 10:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210524_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundry',
            name='total',
            field=models.CharField(default=datetime.datetime(2021, 5, 25, 10, 3, 44, 305410, tzinfo=utc), max_length=50, verbose_name='Total Amount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laundry',
            name='commission',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Refered Byss'),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='custom_number',
            field=models.IntegerField(verbose_name='Customer Number'),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='dropp_off',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='duver_beddings',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duvet and Beddings'),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='duvet',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duvet'),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='native',
            field=models.IntegerField(blank=True, null=True, verbose_name='Complete Native'),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='shirt',
            field=models.IntegerField(blank=True, null=True, verbose_name='T-Shirt'),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='towel',
            field=models.IntegerField(blank=True, null=True, verbose_name='Towel'),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='trouser',
            field=models.IntegerField(blank=True, null=True, verbose_name='Trouser/Short'),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='underwear',
            field=models.IntegerField(blank=True, null=True, verbose_name='Single/Boxers'),
        ),
    ]
