# Generated by Django 2.2.23 on 2021-06-19 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210525_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laundry',
            name='total',
        ),
    ]
